version: '3.1'

services:
  db:
    image: "postgres:14.1"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: somedatabasename
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
